import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '@/utils/cn';
import { headers } from 'next/headers';
import { auth as authentication } from '@/lib/auth';
import { AuthButton, UserControls } from '@/features/auth';
import { Navbar } from '@/components/ui/Navbar';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  const session = await authentication.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body className={cn('antialiased flex flex-col h-dvh', inter.className)}>
        <div className="grid grid-cols-[1fr_min-content_1fr] max-lg:grid-cols-2 items-center p-3 gap-2 mx-auto w-full max-w-7xl">
          <div className="max-lg:hidden">clash.sundell.dev</div>
          <Navbar />
          <div className="flex gap-2 justify-self-end">
            {session ? <UserControls username={session.user.name} /> : <AuthButton />}
          </div>
        </div>
        {children}
        {auth}
      </body>
    </html>
  );
}
