import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/utils/cn";
import Link from "next/link";
import { headers } from "next/headers";
import { auth as authentication } from "@/lib/auth";
import { AuthButton } from "@/features/auth";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  const session = await authentication.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en">
      <body className={cn("antialiased flex flex-col h-dvh", inter.className)}>
        <div className="grid grid-cols-[1fr_min-content_1fr] items-center p-3 mx-auto w-full max-w-7xl">
          <div>clash.sundell.dev</div>
          <div className="flex gap-8 text-primary-dark">
            <Link href="/" className="flex justify-center text-primary">
              Tracking{" "}
              <div className="absolute top-0 w-2 h-1 rounded-b-full border-r border-b border-l bg-accent border-accent" />
            </Link>
            <Link href="/">Calculator</Link>
            <Link href="/">Data</Link>
          </div>
          <div className="flex gap-2 justify-self-end">
            {session ? (
              <>
                <button className="grid place-content-center p-3 rounded-full border transition-colors bg-primary border-primary hover:bg-primary-light">
                  <span className="icon-[solar--settings-linear]" />
                </button>
                <button className="grid place-content-center p-3 rounded-full border transition-colors bg-primary border-primary hover:bg-primary-light">
                  <span className="icon-[solar--repeat-linear]" />
                </button>
                <div className="flex items-center rounded-full border bg-primary border-primary">
                  <div className="pr-3 pl-4 text-text-primary-dark">{session.user.name}</div>
                  <button className="px-3 h-full rounded-full border transition-colors bg-accent border-accent hover:bg-accent">
                    Logout
                  </button>
                </div>
              </>
            ) : (
              <AuthButton />
            )}
          </div>
        </div>
        {children}
        {auth}
      </body>
    </html>
  );
}
